### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by zxcfvb** [raystorm-place/kibana-html-plugin#1]
Kibana will not load after installing this plugin. I had to delete the plugin to get Kibana to come up again. Any ideas what my issue may be? I am using version 4.5.0. 

I noticed someone else was having issues as well, (https://hub.docker.com/r/ibbd/kibana/, if you translate the chinese it says "installation issues").

I'm not sure if it is related but I am having the same problem with the angular js plugin.

**Comment by raystorm-place** [comment]
Version 4.x is not supported here anymore. Please post a new issue if the bug still exist in Kibana 5
