### ISSUE TITLE
6.x version in roadmap SRY Close please

### ISSUE THREAD

**Issue by Shifter2600** [raystorm-place/kibana-html-plugin#13]
Is a 6.x version in roadmap. Is this still an active plugin?

**Comment by jaydabhi17** [comment]
Hi Shifter2600..I have updated html plugin to work on kibana 6.x.
Please refer below link:
https://github.com/jaydabhi17/kibana-html-plugin-6.1.1

**Comment by Shifter2600** [comment]
Awesome. I'm only one plug-in away now in order to update to 6.1. Thx
