### ISSUE TITLE
Can you guide my how to create pull request?

### ISSUE THREAD

**Issue by jaydabhi17** [raystorm-place/kibana-html-plugin#14]
Hi,
I have updated kibana html plugin to work on kibana 6.1.1.
I want to push into its original repository i.e.(raystorm-place/kibana-html-plugin).
You can see my changes here:
https://github.com/jaydabhi17/kibana-html-plugin-6.1.1
Please help me how to do pull request,code review and push changes etc to "raystorm-place/kibana-html-plugin" .
I am new to git.

**Comment by raystorm-place** [comment]
Thank you!
