### ISSUE TITLE
Kibana 6.2.2

### ISSUE THREAD

**Issue by lbegines** [raystorm-place/kibana-html-plugin#15]
Does it work in Kibana v6.2.2? 

Can I change the version in package.json?

**Comment by raystorm-place** [comment]
yes, this should work

**Comment by skipper00** [comment]
I had tryed but it doesn't work. When i have restarted kibana services it wont bind on ip....any sugest? Have you tryed it?

**Comment by lbegines** [comment]
I have just changed the version in package.json and then restarted Kibana and the plugin is working!!
