### ISSUE TITLE
Installation failing, no kibana plugins found in archive

### ISSUE THREAD

**Issue by neilc2016** [raystorm-place/kibana-html-plugin#7]
Hello, trying to install this to a 5.3.1 Kibana instance on linux.  Getting below failure.  The archive does have the plugin files but it's failing to find them. 

> bin/kibana-plugin install file:/vapews/devops/tools/kibana-5614/kibana-html-plugin-master.zip
Attempting to transfer from file:/vapews/devops/tools/kibana-5614/kibana-html-plugin-master.zip
Transferring 74228 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

> ls -lrt kibana-html-plugin-master
total 40K
drwxrwxr-x 2 vapews vapews 4.0K Apr 21 16:03 resources
-rw-rw-r-- 1 vapews vapews  474 Apr 21 16:03 README.md
drwxrwxr-x 2 vapews vapews 4.0K Apr 21 16:03 public
-rw-rw-r-- 1 vapews vapews  137 Apr 21 16:03 package.json
-rw-rw-r-- 1 vapews vapews  570 Apr 21 16:03 LICENSE.md
-rw-rw-r-- 1 vapews vapews  168 Apr 21 16:03 index.js
-rw-rw-r-- 1 vapews vapews  780 Apr 21 16:03 DEVELOPER.md
-rwxr-xr-x 1 vapews vapews  274 Apr 21 16:03 deploy.sh
-rwxr-xr-x 1 vapews vapews  566 Apr 21 16:03 build.sh
-rw-rw-r-- 1 vapews vapews  881 Apr 21 16:03 bower.json

**Comment by azimut** [comment]
looks like latest released zip is for 5.3.0, you will need to use that one with that version or build your own for 5.3.1 (though don't know how do it properly)
